IF EXISTS (SELECT * FROM SYS.VIEWS WHERE NAME = 'VW_FININCIAL_DATA')
BEGIN
    DROP VIEW VW_FININCIAL_DATA;
    PRINT 'EXISTING VIEW VW_FININCIAL_DATA DROPPED.';
END
GO
-- CREATE THE NEW VIEW
CREATE VIEW VW_FININCIAL_DATA AS 
	SELECT F.id_financial_key,
		F.is_active,
		F.dtt_date as dtt_date,
		CONVERT(VARCHAR(10), F.dtt_date, 103) AS st_date,
		F.tx_type,
		F.id_product_name,
		F.id_unit_name,
		F.dec_quantity,
		F.tx_unit,
		F.dec_price,
		PN.TX_VALUE1 AS TX_PRODUCT_NAME,
		UN.TX_VALUE1 AS TX_PRODUCT_UNIT_NAME
	FROM T_FININCIAL_DATA F
	LEFT JOIN 
		T_CONFIGURATION PN ON F.ID_PRODUCT_NAME = PN.ID_CONFIG_KEY AND PN.IS_ACTIVE = 1
	LEFT JOIN 
		T_CONFIGURATION UN ON F.ID_UNIT_NAME = UN.ID_CONFIG_KEY AND UN.IS_ACTIVE = 1
		WHERE F.IS_ACTIVE = 1;
GO


PRINT 'VIEW VW_FININCIAL_DATA CREATED SUCCESSFULLY.';
