package com.softcafesolution.core.enums;

public enum ActionType {

	ACTION_NEW("NEW"),
	
	SEND_EMAIL("SEND_EMAIL"),
	
	DBL_DASHBOARD("DBL_DASHBOARD"),
	
	FILE_COUNT("FILE_COUNT"),
	APPROVE_USER("APPROVE_USER"),
	business_exec("business_exec"),

    ACTION_TAGGED_WITH_CUSTOMER("TAGGED_WITH_CUSTOMER"),
    
	ACTION_VALUE_CONFIG_NEW("VALUE_CONFIG_NEW"),

	ACTION_VALUE_CONFIG_UPDATE("VALUE_CONFIG_UPDATE"),

	ACTION_VALUE_CONFIG_SELECT("VALUE_CONFIG_SELECT"),

	ACTION_VALUE_CONFIG_DELETE("VALUE_CONFIG_DELETE"),
	
	ACTION_NOMANPLATURE_WISE_SELECT("ACTION_NOMANPLATURE_WISE_SELECT"),
	
	ACTION_SELECT("SELECT"),
	ACTION_SELECTALL("SELECT_ALL"),
	ACTION_SEARCH_DISTRIBUTION("SEARCH_DISTRIBUTION"),
	SELECT_BY_DEPARTMENT("SELECT_BY_DEPARTMENT"),
	ACTION_SELECT_RESEND("ACTION_SELECT_RESEND"),
	SEARCH("SEARCH"),
	ACTION_SELECTV2("SELECTV2"),
	ACTION_SAVE("SAVE"),
	SAVE_APPLICATION_SETUP("SAVE_APPLICATION_SETUP"),
	SELECT_ROLE_WITH_PERMISSION("SELECT_ROLE_WITH_PERMISSION"),
	SELECT_BY_TYPE("SELECT_BY_TYPE"),
	SELECT_BY_TYPE_STATUS("SELECT_BY_TYPE_STATUS"),
	ACTION_RAW_MT("ACTION_RAW_MT"),
	EXCEPTION_RAW_MESSAGE("EXCEPTION_RAW_MESSAGE"),
	RAW_MESSAGE("RAW_MESSAGE"),
	ACTION_SELECT_AMMUNITION_TYPE("ACTION_SELECT_AMMUNITION_TYPE"),
	MANAGE_ROLE_PERMISSION("MANAGE_ROLE_PERMISSION"),
	
	
	ACTION_SELECT_SINGLE("SELECT_SINGLE"),
	APPROVE("APPROVE"),
	SAVE_DISTRIBUTION_CONFIG("SAVE_DISTRIBUTION_CONFIG"),
	SELECT_GROUP_USERS("SELECT_GROUP_USERS"),
	SELECT_GROUP_CUSTOMER("SELECT_GROUP_CUSTOMER"),
	SELECT_ROLE_GROUP_LIST("SELECT_ROLE_GROUP_LIST"),
	SELECT_GROUP_MT("SELECT_GROUP_MT"),
	SELECT_UNMAPED_GROUP_USERS("SELECT_UNMAPED_GROUP_USERS"),
	SELECT_UNMAPED_GROUP_MT("SELECT_UNMAPED_GROUP_MT"),
	MAP("MAP"),
	MAP_NEW("MAP_NEW"),
	UNMAP_ONE("UNMAP_ONE"),
	REMOVE_SELECTED_GROUP_CUSTOMER("REMOVE_SELECTED_GROUP_CUSTOMER"),
	ACTION_SEARCH("SEARCH"),

	ACTION_SELECT_1("SELECT_1"),
	SELECT_BY_AMMO_TYPE ("SELECT_BY_AMMO_TYPE"),

	ACTION_SELECT_2("SELECT_2"),

	ACTION_SELECT_3("SELECT_3"),
	
	ACTION_SELECT_APPROVE("ACTION_SELECT_APPROVE"),
	
	ACTION_SELECT_2_EXPLOSIVE_TYPE("ACTION_SELECT_2_EXPLOSIVE_TYPE"),

	ACTION_SELECT_2_ROUND_TYPE("ACTION_SELECT_2_ROUND_TYPE"),
	ACTION_ITEM_WISE_SELECT("ACTION_ITEM_WISE_SELECT"),

	SELECT_2_TYPE_OF_AMMUNITION_SAFETY_DISTANCE("SELECT_2_TYPE_OF_AMMUNITION_SAFETY_DISTANCE"),

	SELECT_SEARCH("SELECT_SEARCH"),

	SEARCH_BY_TEXT("SEARCH_BY_TEXT"),

	SEARCH_OR_DATA_FOR_LIST("SEARCH_OR_DATA_FOR_LIST"),
	LOAD_AMMO_TYPE_GROUP("LOAD_AMMO_TYPE_GROUP"),
	

	SEARCH_AMMUNATION_DATA_FOR_LIST("SEARCH_AMMUNATION_DATA_FOR_LIST"),

	SEARCH_AMMUNATION_DATA("SEARCH_AMMUNATION_DATA"),
	SEARCH_DATA_FOR_AMMO_REPORT("SEARCH_DATA_FOR_AMMO_REPORT"),

	AMMUNATION_SEARCH_DATA_REPORT("AMMUNATION_SEARCH_DATA_REPORT"),

	SEARCH_DATA_FOR_LIST_PDF("SEARCH_DATA_FOR_LIST_PDF"),

	SEARCH_DATA_FOR_NEQ_CALCULATION("SEARCH_DATA_FOR_NEQ_CALCULATION"),

	ACTION_SELECT_ALL_HAVE_AMMO_TYPE_ID("SELECT_ALL_HAVE_AMMO_TYPE_ID"),
	ACTION_SELECT_ALL_NOMANCLATURE("ACTION_SELECT_ALL_NOMANCLATURE"),
	

	EXCEL_EXPORT("EXCEL_EXPORT"),

	SELECT_SINGLE("SELECT_SINGLE"),
	
	LDAP_LOGIN_NAME_CHECK("LDAP_LOGIN_NAME_CHECK"),
	
	ACTION_SELECT_ALL("SELECT_ALL"),

	INACTIVE_ALL("INACTIVE_ALL"),

	ACTION_DELETE("DELETE"),
	IS_ASSIGN_ROLE("IS_ASSIGN_ROLE"),
	ACTION_APPROVE("APPROVE"),
	LOAD_PERMISSION("LOAD_PERMISSION"),
	
	
	CUSTOMER_APPROVE("CUSTOMER_APPROVE"),

	ACTION_INCIDENT_COUNT("INCIDENT_COUNT"),

	ACTION_MANAGE_ROLE("MANAGE_ROLE"),
	ACTION_MANAGE_ROLE_GROUP("MANAGE_ROLE_GROUP"),
	
	MANAGE_ROLE_GROUP("MANAGE_ROLE_GROUP"),
	
	ACTION_MANAGE_USER_APP("MANAGE_APP"),
	
	

	ACTION_SELECT_SINGLE_WITH_ROLE("SELECT_SINGLE_WITH_ROLE"),
	SELECT_SINGLE_WITH_ROLE_GROUP("SELECT_SINGLE_WITH_ROLE_GROUP"),
	SELECT_USER_APP("SELECT_USER_APP"),
	REGISTER("REGISTER"),
	
	

	ACTION_UPDATE("UPDATE"),
	ACTION_UPDATE_2("UPDATE_2"),
	

	ACTION_LOGIN("LOGIN"),

	ACTION_LOGOUT("LOGOUT"),

	ACTION_RESET_PASS("RESET_PASS"),

	ACTION_CHANGE_PASS("CHANGE_PASS"),

	ACTION_FORGOT_PASS("FORGOT_PASS"),

	ACTION_AUTH_FORGOT_PASS("AUTH_FORGOT_PASS"),

	ACTION_SELECT_USER_ROLE("SELECT_USER_ROLE"),

	ACTION_ALL_OVERVIEW("ALL_OVERVIEW"),

	ACTION_TOGGLE_ACTIVATION("TOGGLE_ACTIVATION"),

	ACTION_TOGGLE_2_FA("TOGGLE_2_FA"),
	ACTION_SELECT_USER_ALL_APP("SELECT_USER_ALL_APP"),

	ACTION_VERIFY_LOGIN_2_FA("VERIFY_LOGIN_2_FA"),

	ACTION_RESEND_2FA_CODE("RESEND_2FA_CODE"),

	ACTION_LOAD_LOCATION("LOAD_LOCATION"),

	SEARCH_LOADTABLE_DATA_FOR_LIST("SEARCH_LOADTABLE_DATA_FOR_LIST"),

	SEARCH_LOADTABLE_DATA("SEARCH_LOADTABLE_DATA"),

	LOADTABLE_SEARCH_DATA_REPORT("LOADTABLE_SEARCH_DATA_REPORT"),
	BRUNCH_LIST("BRUNCH_LIST"),
	STATE_LIST("STATE_LIST"),
	
	DELETE_MULTI_BANK_NAME("DELETE_MULTI_BANK_NAME"), // Al-Amin
	UPDATE_MULTI_BANK_NAME("UPDATE_MULTI_BANK_NAME"), // Al-Amin
	
	SELECT_ALL_ITEM_NO("SELECT_ALL_ITEM_NO"), 
	SELECT_PERMISSION_ROLE("SELECT_PERMISSION_ROLE"), 
	MANAGE_APP_PERMISSION("MANAGE_APP_PERMISSION"), 
	PEND_MAIL_DETAILS("PEND_MAIL_DETAILS"), 
	APPROVE_ROLE("APPROVE_ROLE"),
	APPROVE_DEASSIGN("APPROVE_DEASSIGN"),
	APPROVE_PERMISSION("APPROVE_PERMISSION"),
	APPROVE_DEASSIGN_PERMISSION("APPROVE_DEASSIGN_PERMISSION"),
    USER_ACTIVATION("USER_ACTIVATION"),
    SELECT_BANK_NAME("SELECT_BANK_NAME"),
	DISTINCT_BRAND("DISTINCT_BRAND"),
	DISTINCT_TYPE("DISTINCT_TYPE"),
	SELECT_BANK_BIN("SELECT_BANK_BIN"),
	UPDATE("UPDATE"), 
	ACTION_SEARCH_MONTH_INTERVAL("SEARCH_MONTH"), 
	ACTION_SEARCH_YEARLY_INTERVAL("SEARCH_YEARLY"),
	ACTION_SEARCH_MONTH_COMPARE("SEARCH_MONTHLY_COMPARE"), 
	ACTION_SEARCH_YEARLY_COMPARE("SEARCH_YEARLY_COMPARE"), 
	ACTION_SEARCH_MAP("SEARCH_MAP"), 
	LOAD_PRODUCTS_NAME("LOAD_PRODUCTS_NAME"),
	SELECT_BY_ID("SELECT_BY_ID"), 
	TABULAR_SEARCH("TABULAR_SEARCH"), 
	LOAD_EXTRA("LOAD_EXTRA");
	
	
	
	

	private final String actionType;

	private ActionType(String actionType) {
		this.actionType = actionType;
	}

	@Override
	public String toString() {
		return actionType;
	}

}
